### ISSUE TITLE
Promotion is failed sort of sliently

### ISSUE THREAD

**Issue by wanghong230** [akuity/kargo#1774] opened 2024-04-05 03:43 UTC
Click one freight to promote.
(The promtion actually failed due to credential error).
You won't be able to tell anything has happened. (The stage is showing healthy)
Until you click into the stage detail, and check the last promotion error state.

![image](https://github.com/akuity/kargo/assets/2680725/97b36f0a-7449-4c6d-a43a-f60c90580b8d)

**Comment by wanghong230** [comment] 2024-04-05 03:44
I think the last promotion status should be surfaced in the top object.

**Comment by jessesuen** [comment] 2024-04-05 05:02
Duplicate of https://github.com/akuity/kargo/issues/1207

**Closed by jessesuen** 2024-04-05 05:02 UTC
Labels: kind/bug, needs/priority, needs/area
