### ISSUE TITLE
Remove gitops engine and argocd dependency

### ISSUE THREAD

**Issue by alexmt** [akuity/kargo#524] opened 2023-08-08 01:55 UTC
Kargo imports github.com/argoproj/argo-cd and github.com/argoproj/gitops-engine mostly to evaluate Argo CD application health (and sync status).

This has two caveats:  Kargo depends on a particular Argo CD version (v2.6 as of today), and it depends on the whole Kubernetes. 

# Proposal

Argo CD application structure is stable and not changing frequently anymore. I'm proposing to copy application type definition with minimal set of required fields and remove dependency on gitops engine and argocd  repos

**Comment by jessesuen** [comment] 2023-08-08 02:00
> I'm proposing to copy application type definition with minimal set of required fields

Oops, I just reread this part. I think you and I are saying the same thing.

**Comment by krancour** [comment] 2023-08-08 16:45
Thinking about this more, I'm not sure this slims down the dependencies much, if at all.

`github.com/argoproj/argo-cd` is used for more than what is described here.

Non-exhaustively, it is also used for a reconciler that listens changes in `Application` state, forcing sync/refresh of an `Application`, and it is also used indirectly via Bookkeeper. (Kargo uses Bookkeeper as a library and Bookkeeper uses the Argo CD repo server as a library.)

**Comment by krancour** [comment] 2023-11-16 15:34
#956 is a duplicate of this, but most of the work's been tracked there, so I'm closing this one.

**Closed by krancour** 2023-11-16 15:34 UTC
Labels: kind/refactor, priority/normal, area/tech-debt
