### ISSUE TITLE
Image Selection appears too flexible

### ISSUE THREAD

**Issue by phclark** [akuity/kargo#1153] opened 2023-11-21 02:11 UTC
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `kargo version`.
* [ ] I've pasted logs, if applicable.

# Description

When running through the quickstart with 0.2.0, I modified the Warehouse semverConstraint to include more than one images from the image repository. I would expect that I would only be able to "pull" Freight currently in use by the upstream stage, but I was able to select any piece of Freight in the freighline. For example, I clicked the pull button in the `uat` stage, and was able to `d9a3e3e` when the `test` stage used `3104320`. 

Additionally, when "pushing", I would expect my only option would be to push the current freight. However, when I select the push button on the `uat` stage, I'm able to push `47b33c0` when I would expect to only be able to push the current freight, `d9a3e3e`.

Note that I have gone through the 
# Screenshots

<img width="1051" alt="image" src="https://github.com/akuity/kargo/assets/35117115/572be628-23d3-420f-8f20-1f5aa28021c0">

<img width="1047" alt="image" src="https://github.com/akuity/kargo/assets/35117115/2a629887-2d2f-42ed-80c3-2174c7cac9ac">

# Steps to Reproduce

1. Follow the Quickstart for version 0.2.0, https://kargo.akuity.io/quickstart
2. Edit the `kargo-demo` Warehouse's `semverConstraint` to match multiple images:
```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-demo
  namespace: kargo-demo
spec:
  subscriptions:
    - image:
        repoURL: nginx
        semverConstraint: ~1.25.0
        updateStrategy: SemVer
```

# Version

```
Client Version: v0.2.1
Server Version: v0.2.1
```

# Logs

```
Paste any relevant application logs here.
```

**Comment by krancour** [comment] 2023-11-21 04:22
@phclark I'm sorry I didn't catch this sooner when you brought it up on Discord...

I think this may actually be a misunderstanding.

By design, you can "pull" _any_ freight into a stage as long as it has already qualified in the upstream stage(s) to which that stage subscribes. It is not limited to the freight that are _currently_ in those immediately upstream stages.

Likewise, you can "push" _any_ freight that has already qualified in the stage from which you are pushing. It is not limited to the freight that is currently in that stage.

I mentioned this being by design. This is, for instance, how one might perform a "rollback" -- by selecting a previous freight. It also provides some flexibility. Consider the possibility that something has made its way all the way through to the last stage before prod (let's call it "uat") and has qualified in that stage. The decision to promote that to prod has been made, but the promotion is delayed for whatever reason. In the meantime, the product owner _really_ wants the next release candidate deployed to uat. Maybe she even does it herself. The flexibility to promote more than what is _currently_ immediately upstream ends up allowing you to handle this scenario.

Actionable things here, though:

* At the very least, the docs (admittedly still a WIP) need to be very clear on how "available" is defined.

* The terms "push" and "pull" certainly hint that you are constrained to pulling from what's immediately upstream and to pushing what you currently have. In fact, "push" and "pull" aren't official terms (it's not anywhere in the code or docs), but we've tended to casually use it in conversations, mainly to explain the difference between the target button and the truck button, which has been a frequent question. I think this confusion is clear impetus for no longer throwing those two terms around so casually.

* Whether it is reworking the icons on those buttons, the alt text for the buttons, or some other UI changes, we may be able to do _something_ to clarify things. It could be something as simple as a thin banner that appears above the freightline during promotion, saying something like, "These Freight have all qualified in the Stages immediately upstream from `x`." I'm no UI expert though. I defer to @rbreeze for better ideas of how me might visually clear up this confusion.

@phclark thank you for bringing this to our attention!

**Comment by krancour** [comment] 2023-11-21 14:32
See previous comment. This is now broken into smaller, more actionable issues, so I'm closing this.

Thanks again @phclark!

**Closed by krancour** 2023-11-21 14:32 UTC
Labels: kind/bug, area/documentation, area/ui, priority/normal
