### ISSUE TITLE
GitRepoUpdate with kargo-render updates all instances of an image, instead of only the target app

### ISSUE THREAD

**Issue by BasJ93** [akuity/kargo#2371] opened 2024-07-31 09:31 UTC
# Checklist

* [X] I've searched the issue queue to verify this is not a duplicate bug report.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `kargo version`.
* [X] I've pasted logs, if applicable.

# Description

When using kargo-render with a repo that has multiple applications using the same image in the same environment, kargo-render updates all the images instead of only the image of the application/stage that initiated the promotion.

I.E. have two applications running nginx:
 - app-a
 - app-b

Create a promotion for app-a to a newer version of the nginx image, and check the generated manifests. The manifest for app-b will now also contain the new image version.

# Steps to Reproduce

I.E. have two applications running nginx:
 - app-a
 - app-b

Create a promotion for app-a to a newer version of the nginx image, and check the generated manifests. The manifest for app-b will now also contain the new image version.

# Version

Kargo v0.7.0

# Remarks

I see that for promotions through Kustomize, a path parameter can be provided. Would something similar be possible for kargo-render? I would expect something akin to this idea to solve my problem as kargo-render is only run on the target app.

**Comment by krancour** [comment] 2024-07-31 10:51
This sounds like a Kargo Render configuration issue. The idea behind Kargo Render is to keep the rules for how a branch is rendered close to the config itself in the kargo-render.yaml file.

Can you show me what the layout of your gitops repo looks like, as well as what your kargo-render.yaml looks like?

**Comment by krancour** [comment] 2024-07-31 14:28
Ah. Ok. You are doing everything correctly.

I've realized now what the issue is.

Helm doesn't have a nice equivalent to `kustomize edit set image`, so we made a decision fairly early on that rendering will occur in _two_ passes. In the first pass, we use whichever config management tool _you_ are using. So it's either a `helm template` command or a `kustomize build` command. _After that_ we take a second pass, performing `kustomize edit set image` and `kustomize build` on the results of the first pass to produce the final result.

Your issue is occurring in the second pass.

Regrettably, this is not _easily_ fixed, but I will put some further thought into this.

**Comment by BasJ93** [comment] 2024-07-31 14:37
Hmm, that's a shame.

If possible I'd like to help out with this, as it is currently blocking us from taking Kargo in to general use.

**Comment by krancour** [comment] 2024-07-31 16:17
> If possible I'd like to help out with this, as it is currently blocking us from taking Kargo in to general use.

The honest answer here is that the future of Kargo Render is somewhat uncertain:

* Our current plans for v0.9.0 may make it more attractive to just use Kustomize outright.
* If it doesn't go away entirely, I suspect Kargo Render will go through some radical simplification soon, as it is currently capable of a lot _besides_ rendering. It can check out the source branch, render, then write to the target branch. Kargo itself uses Kargo Render in a way where Kargo Render isn't responsible for any checking out or pushing. So basically, there's a lot of unnecessary functionality in the tool that may be dropped. As those features get dropped, Kargo Render starts to look more and more like it's not doing much _besides_ just running Kustomize or Helm, which brings me back to the previous bullet. Maybe it is about to become much more attractive to just use Kustomize or Helm more directly.

> As a side note, the target apps in this case are all kustomize capable. Could we maybe do something with that?

Yes. I'm not at a point of suggesting everyone abandon Kargo Render entirely, but given my uncertainty _and_ your constraints, it may be better for your use case to use Kustomize more directly.

**Comment by BasJ93** [comment] 2024-08-01 06:49
> Yes. I'm not at a point of suggesting everyone abandon Kargo Render entirely, but given my uncertainty and your constraints, it may be better for your use case to use Kustomize more directly.

Please correct me if I'm wrong, but when I try to use the direct Kustomize option in Kargo, I end up with a copy of my entire `main` branch in my environment branch. The thing I don't want, and why I ended up choosing the `render` option. Is it possible to still have the rendered manifests result when using Kustomize directly in Kargo?

**Comment by krancour** [comment] 2024-08-01 12:52
At present, no. After v0.9.0, yes.

**Comment by krancour** [comment] 2024-10-07 17:53
Closing as no longer relevant since Kargo Render's usefulness is diminished in v0.9.0 and support will be dropped along with the legacy promotion mechanisms in v1.0.0.

**Closed by krancour** 2024-10-07 17:53 UTC
Labels: kind/bug, priority/low, needs/area
