### ISSUE TITLE
Stage health status showing unhealthy despite being synced to correct sha

### ISSUE THREAD

**Issue by morey-tech** [akuity/kargo#807] opened 2023-09-20 15:26 UTC
The status is unhealthy because the Application is **not** synced to revision `6d13e269dc243335bf098f505d1e12214a301fe5`. I can't find where this revision is coming from.

The freight for the stage shows `ec31f4da8e81e8b8b5446c9d0a56559cfcfff5f5`, which is what the Application is synced to.

<details><summary>Screenshots inside!</summary>

![Xnapper-2023-09-20-11 07 37](https://github.com/akuity/kargo/assets/4213435/607c16c8-7274-409b-bdea-ef7c0cc3a3b6)
![Xnapper-2023-09-20-11 03 13](https://github.com/akuity/kargo/assets/4213435/b7ff8852-8170-4b94-8aea-e1e368f6efcc)
![Xnapper-2023-09-20-11 08 50](https://github.com/akuity/kargo/assets/4213435/3cb0ab00-0768-4b92-8105-ac7749027609)
</details>

<details><summary>Live Kargo `Stage` manifest inside!</summary>

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo
  uid: 54ed2308-b87b-4010-8cd1-fb29efdbdafb
  resourceVersion: "68748"
  generation: "4"
  creationTimestamp: 2023-09-19T16:33:09Z
  labels:
    argocd.argoproj.io/instance: kargo-stages
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"kargo.akuity.io/v1alpha1","kind":"Stage","metadata":{"annotations":{},"labels":{"argocd.argoproj.io/instance":"kargo-stages"},"name":"test","namespace":"kargo-demo"},"spec":{"promotionMechanisms":{"argoCDAppUpdates":[{"appName":"kargo-demo-test","appNamespace":"argocd"}],"gitRepoUpdates":[{"kustomize":{"images":[{"image":"nginx","path":"stages/test"}]},"repoURL":"https://github.com/morey-tech/kargo-demo/","writeBranch":"stages/test"}]},"subscriptions":{"repos":{"git":[{"branch":"main","repoURL":"https://github.com/morey-tech/kargo-demo/"}],"images":[{"repoURL":"nginx","semverConstraint":"^1.24.0","updateStrategy":"SemVer"}]}}}}
spec:
  subscriptions:
    repos:
      git:
        - repoURL: https://github.com/morey-tech/kargo-demo/
          branch: main
      images:
        - repoURL: nginx
          updateStrategy: SemVer
          semverConstraint: ^1.24.0
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://github.com/morey-tech/kargo-demo/
        writeBranch: stages/test
        kustomize:
          images:
            - image: nginx
              path: stages/test
    argoCDAppUpdates:
      - appName: kargo-demo-test
        appNamespace: argocd
status:
  availableFreight:
    - id: c7b360e96c684f446fa41821eae101f6a9a4bbdc
      firstSeen: 2023-09-20T14:59:22Z
      commits:
        - repoURL: https://github.com/morey-tech/kargo-demo/
          id: ec31f4da8e81e8b8b5446c9d0a56559cfcfff5f5
          branch: main
          message: "fix(kargo): switch to valuesObject"
      images:
        - repoURL: nginx
          tag: 1.25.2
      qualified: true
    - id: b81563ef088ab61aeefc01af49b7ae3560c815ee
      firstSeen: 2023-09-20T14:56:57Z
      commits:
        - repoURL: https://github.com/morey-tech/kargo-demo/
          id: 7a2245e561eb2b5aff8db86e8235f2a0635415a9
          branch: main
          message: "fix(kargo): remove escapes"
      images:
        - repoURL: nginx
          tag: 1.25.2
      qualified: true
    - id: 544a0c7f81a56f9167a117e5719ac0874fd73a1a
      firstSeen: 2023-09-20T14:54:44Z
      commits:
        - repoURL: https://github.com/morey-tech/kargo-demo/
          id: daad8ed5511f72a70eed7e84c2ecef4c7455c0ac
          branch: main
          message: "fix(kargo): map to empty string"
      images:
        - repoURL: nginx
          tag: 1.25.2
      qualified: true
    - id: bb61527632d6199d49895c7c80036d5dfb18787d
      firstSeen: 2023-09-20T14:49:10Z
      commits:
        - repoURL: https://github.com/morey-tech/kargo-demo/
          id: 0a64e58cc067594e407586ee38de7b8eb4117587
          branch: main
          message: "fix(kargo): parameter is map"
      images:
        - repoURL: nginx
          tag: 1.25.2
      qualified: true
    - id: e578fa506e2226bad4aeb38f5c816ee930dd989b
      firstSeen: 2023-09-20T14:46:55Z
      commits:
        - repoURL: https://github.com/morey-tech/kargo-demo/
          id: e0b42c63115a0e63c51a65d90851f2ec54fbb432
          branch: main
          message: "feat(kargo): enable argocd deep-links"
      images:
        - repoURL: nginx
          tag: 1.25.2
      qualified: true
    - id: bb33a5fcd71235feaf9d8025e4a475d542b9f074
      firstSeen: 2023-09-20T14:43:45Z
      commits:
        - repoURL: https://github.com/morey-tech/kargo-demo/
          id: 29d0fd8ed88ad4c0b9695fcf06f7daba26e94d3e
          branch: main
          message: "fix(stage): write test to test branch"
      images:
        - repoURL: nginx
          tag: 1.25.2
      qualified: true
    - id: b84805de51c0410525e916130cd1bde754040d13
      firstSeen: 2023-09-20T14:33:34Z
      commits:
        - repoURL: https://github.com/morey-tech/kargo-demo/
          id: d4da2a80004bd34cd6379a7e63474126010fd38f
          branch: main
          message: "feat(test): add h2 heading"
      images:
        - repoURL: nginx
          tag: 1.25.2
      qualified: true
    - id: 489940670ccb6a1d0e96d9ed06b0a0b428ee1fcf
      firstSeen: 2023-09-20T14:27:28Z
      commits:
        - repoURL: https://github.com/morey-tech/kargo-demo/
          id: 78e9f589f090a5c6f4b60a443078d0460e00ae6e
          branch: main
          message: "feat(stages): test subscribed to git"
      images:
        - repoURL: nginx
          tag: 1.25.2
      qualified: true
    - id: b73f9d1afaca87254b64e64e5439557e86dcba79
      firstSeen: 2023-09-19T16:33:10Z
      images:
        - repoURL: nginx
          tag: 1.25.2
      qualified: false
  currentFreight:
    id: c7b360e96c684f446fa41821eae101f6a9a4bbdc
    firstSeen: 2023-09-20T14:59:22Z
    commits:
      - repoURL: https://github.com/morey-tech/kargo-demo/
        id: ec31f4da8e81e8b8b5446c9d0a56559cfcfff5f5
        branch: main
        healthCheckCommit: 6d13e269dc243335bf098f505d1e12214a301fe5
        message: "fix(kargo): switch to valuesObject"
    images:
      - repoURL: nginx
        tag: 1.25.2
    qualified: false
  history:
    - id: c7b360e96c684f446fa41821eae101f6a9a4bbdc
      firstSeen: 2023-09-20T14:59:22Z
      commits:
        - repoURL: https://github.com/morey-tech/kargo-demo/
          id: ec31f4da8e81e8b8b5446c9d0a56559cfcfff5f5
          branch: main
          healthCheckCommit: 6d13e269dc243335bf098f505d1e12214a301fe5
          message: "fix(kargo): switch to valuesObject"
      images:
        - repoURL: nginx
          tag: 1.25.2
      qualified: false
    - id: b81563ef088ab61aeefc01af49b7ae3560c815ee
      firstSeen: 2023-09-20T14:56:57Z
      commits:
        - repoURL: https://github.com/morey-tech/kargo-demo/
          id: 7a2245e561eb2b5aff8db86e8235f2a0635415a9
          branch: main
          healthCheckCommit: 152d43f0fee9d85a32589069a58e85d650b135f9
          message: "fix(kargo): remove escapes"
      images:
        - repoURL: nginx
          tag: 1.25.2
      qualified: false
    - id: 544a0c7f81a56f9167a117e5719ac0874fd73a1a
      firstSeen: 2023-09-20T14:54:44Z
      commits:
        - repoURL: https://github.com/morey-tech/kargo-demo/
          id: daad8ed5511f72a70eed7e84c2ecef4c7455c0ac
          branch: main
          healthCheckCommit: db51e64adafefcb11de135e1d65a7f05bec68f0c
          message: "fix(kargo): map to empty string"
      images:
        - repoURL: nginx
          tag: 1.25.2
      qualified: false
    - id: bb61527632d6199d49895c7c80036d5dfb18787d
      firstSeen: 2023-09-20T14:49:10Z
      commits:
        - repoURL: https://github.com/morey-tech/kargo-demo/
          id: 0a64e58cc067594e407586ee38de7b8eb4117587
          branch: main
          healthCheckCommit: 0b5ab95b3acd0af52598e894c338c3f171c18e9d
          message: "fix(kargo): parameter is map"
      images:
        - repoURL: nginx
          tag: 1.25.2
      qualified: false
    - id: e578fa506e2226bad4aeb38f5c816ee930dd989b
      firstSeen: 2023-09-20T14:46:55Z
      commits:
        - repoURL: https://github.com/morey-tech/kargo-demo/
          id: e0b42c63115a0e63c51a65d90851f2ec54fbb432
          branch: main
          healthCheckCommit: 1e20405209d0831c70c0191d53eaff301e30c985
          message: "feat(kargo): enable argocd deep-links"
      images:
        - repoURL: nginx
          tag: 1.25.2
      qualified: false
    - id: bb33a5fcd71235feaf9d8025e4a475d542b9f074
      firstSeen: 2023-09-20T14:43:45Z
      commits:
        - repoURL: https://github.com/morey-tech/kargo-demo/
          id: 29d0fd8ed88ad4c0b9695fcf06f7daba26e94d3e
          branch: main
          healthCheckCommit: 0118dffc84eb9778f1beed198a4556f767f3dd2f
          message: "fix(stage): write test to test branch"
      images:
        - repoURL: nginx
          tag: 1.25.2
      qualified: false
    - id: b73f9d1afaca87254b64e64e5439557e86dcba79
      firstSeen: 2023-09-19T16:33:10Z
      images:
        - repoURL: nginx
          tag: 1.25.2
      qualified: true
  health:
    status: Unhealthy
    issues:
      - Argo CD Application "kargo-demo-test" in namespace "argocd" is not
        synced to revision "6d13e269dc243335bf098f505d1e12214a301fe5"
    argoCDApps:
      - namespace: argocd
        name: kargo-demo-test
        healthStatus:
          status: Healthy
        syncStatus:
          status: Synced
          revision: ec31f4da8e81e8b8b5446c9d0a56559cfcfff5f5
```
</details>

<details><summary>Live Argo CD `Application` manifest inside!</summary>

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    kargo.akuity.io/authorized-stage: kargo-demo:test
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{"kargo.akuity.io/authorized-stage":"kargo-demo:test"},"name":"kargo-demo-test","namespace":"argocd"},"spec":{"destination":{"namespace":"kargo-demo-test","server":"https://kubernetes.default.svc"},"project":"default","source":{"path":"stages/test","repoURL":"https://github.com/morey-tech/kargo-demo/","targetRevision":"main"}}}
  creationTimestamp: "2023-09-19T16:31:40Z"
  generation: 248
  name: kargo-demo-test
  namespace: argocd
  resourceVersion: "70381"
  uid: d7921ddd-ab4a-4f9b-bf04-ee0a76a22a7e
spec:
  destination:
    namespace: kargo-demo-test
    server: https://kubernetes.default.svc
  project: default
  source:
    path: stages/test
    repoURL: https://github.com/morey-tech/kargo-demo/
    targetRevision: main
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  history:
  - deployStartedAt: "2023-09-19T16:33:22Z"
    deployedAt: "2023-09-19T16:33:22Z"
    id: 0
    revision: 896845d99fc3b566c02fc1068fe98e6ebb52238e
    source:
      path: stages/test
      repoURL: https://github.com/morey-tech/kargo-demo/
      targetRevision: main
  - deployStartedAt: "2023-09-20T14:43:55Z"
    deployedAt: "2023-09-20T14:43:55Z"
    id: 1
    revision: 29d0fd8ed88ad4c0b9695fcf06f7daba26e94d3e
    source:
      path: stages/test
      repoURL: https://github.com/morey-tech/kargo-demo/
      targetRevision: main
  - deployStartedAt: "2023-09-20T14:47:04Z"
    deployedAt: "2023-09-20T14:47:05Z"
    id: 2
    revision: e0b42c63115a0e63c51a65d90851f2ec54fbb432
    source:
      path: stages/test
      repoURL: https://github.com/morey-tech/kargo-demo/
      targetRevision: main
  - deployStartedAt: "2023-09-20T14:49:14Z"
    deployedAt: "2023-09-20T14:49:14Z"
    id: 3
    revision: 0a64e58cc067594e407586ee38de7b8eb4117587
    source:
      path: stages/test
      repoURL: https://github.com/morey-tech/kargo-demo/
      targetRevision: main
  - deployStartedAt: "2023-09-20T14:54:54Z"
    deployedAt: "2023-09-20T14:54:55Z"
    id: 4
    revision: daad8ed5511f72a70eed7e84c2ecef4c7455c0ac
    source:
      path: stages/test
      repoURL: https://github.com/morey-tech/kargo-demo/
      targetRevision: main
  - deployStartedAt: "2023-09-20T14:57:04Z"
    deployedAt: "2023-09-20T14:57:05Z"
    id: 5
    revision: 7a2245e561eb2b5aff8db86e8235f2a0635415a9
    source:
      path: stages/test
      repoURL: https://github.com/morey-tech/kargo-demo/
      targetRevision: main
  - deployStartedAt: "2023-09-20T14:59:24Z"
    deployedAt: "2023-09-20T14:59:25Z"
    id: 6
    revision: ec31f4da8e81e8b8b5446c9d0a56559cfcfff5f5
    source:
      path: stages/test
      repoURL: https://github.com/morey-tech/kargo-demo/
      targetRevision: main
  - deployStartedAt: "2023-09-20T15:01:19Z"
    deployedAt: "2023-09-20T15:01:19Z"
    id: 7
    revision: ec31f4da8e81e8b8b5446c9d0a56559cfcfff5f5
    source:
      path: stages/test
      repoURL: https://github.com/morey-tech/kargo-demo/
      targetRevision: main
  operationState:
    finishedAt: "2023-09-20T15:01:19Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        username: admin
      retry: {}
      sync:
        revision: ec31f4da8e81e8b8b5446c9d0a56559cfcfff5f5
        syncStrategy:
          hook: {}
    phase: Succeeded
    startedAt: "2023-09-20T15:01:19Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: ConfigMap
        message: configmap/kargo-demo-content unchanged
        name: kargo-demo-content
        namespace: kargo-demo-test
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/kargo-demo unchanged
        name: kargo-demo
        namespace: kargo-demo-test
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/kargo-demo unchanged
        name: kargo-demo
        namespace: kargo-demo-test
        status: Synced
        syncPhase: Sync
        version: v1
      revision: ec31f4da8e81e8b8b5446c9d0a56559cfcfff5f5
      source:
        path: stages/test
        repoURL: https://github.com/morey-tech/kargo-demo/
        targetRevision: main
  reconciledAt: "2023-09-20T15:18:43Z"
  resources:
  - kind: ConfigMap
    name: kargo-demo-content
    namespace: kargo-demo-test
    status: Synced
    version: v1
  - health:
      status: Healthy
    kind: Service
    name: kargo-demo
    namespace: kargo-demo-test
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: kargo-demo
    namespace: kargo-demo-test
    status: Synced
    version: v1
  sourceType: Kustomize
  summary:
    images:
    - nginx:1.25.2
  sync:
    comparedTo:
      destination:
        namespace: kargo-demo-test
        server: https://kubernetes.default.svc
      source:
        path: stages/test
        repoURL: https://github.com/morey-tech/kargo-demo/
        targetRevision: main
    revision: ec31f4da8e81e8b8b5446c9d0a56559cfcfff5f5
    status: Synced
```
</details>

**Comment by morey-tech** [comment] 2023-09-20 15:51
Okay, I found the issue.

```yaml
        healthCheckCommit: 6d13e269dc243335bf098f505d1e12214a301fe5
```

![Xnapper-2023-09-20-11 49 47](https://github.com/akuity/kargo/assets/4213435/35f1e1e5-4f12-4e54-8354-b085a188e6f4)

This commit SHA is for the `stage/test` branch, used for the `writeBranch` of the promotion mechanism. And since the `Application` isn't set to target that branch, the health check fails.

**Comment by morey-tech** [comment] 2023-09-20 16:07
Interestingly, after pushing a new commit to `main`, the stage auto-updated and shows healthy. Despite the application not being synced to the health check commit (`689486687a3c9928e0d07e8880e1538c2649a7bd`) of the current freight (with commit id `6380a90784c45eacf9f3defe609d59a371e6bc69`, which is what it is synced to).

**Comment by krancour** [comment] 2023-09-20 19:47
Do you have manifests that reproduce this?

**Comment by morey-tech** [comment] 2023-09-20 19:50
> Do you have manifests that reproduce this?

I've included the `Stage` and `Application` manifests in the description of the issue. However, I haven't tested reproducing this yet.

**Comment by krancour** [comment] 2023-09-20 20:15
> Interestingly, after pushing a new commit to main, the stage auto-updated and shows healthy. Despite the application not being synced to the health check commit (689486687a3c9928e0d07e8880e1538c2649a7bd) of the current freight (with commit id 6380a90784c45eacf9f3defe609d59a371e6bc69, which is what it is synced to).

The manifests didn't look like they reflected this.

**Comment by krancour** [comment] 2023-09-21 17:44
Ok... so initial issue was explained... current issue is the opposite... looks healthy, but shouldn't be?

I'll look into this.

**Comment by krancour** [comment] 2023-09-23 00:00
Found it...

What revision the App is synced to only factors into health if we can match the App's repo URL to a repo URL in a freight. i.e. We only factor this in if we know what revision we really _want_ the App synced to.

There's no match here because... wait for it...

You subscribed to `https://github.com/morey-tech/kargo-demo/`, but the repo URL in your App is `https://github.com/morey-tech/kargo-demo`. (One has a trailing slash and the other doesn't.)

There is an established method of canonicalizing repo URLs that should be applied before all comparisons and it's been missed here. It's likely been missed in other places as well.

I'm going to close this issue and open a more general one about making sure this is accounted for everywhere.

**Comment by krancour** [comment] 2023-09-23 00:03
Superceeded by #838

**Closed by krancour** 2023-09-23 00:03 UTC
Labels: kind/bug, priority/normal, area/controller
