### ISSUE TITLE
Value of local API server feature in CLI

### ISSUE THREAD

**Issue by hiddeco** [akuity/kargo#1569] opened 2024-03-04 22:37 UTC
At present, the `kargo` CLI supports a "local API server" mode for certain commands when `--local-server` is provided. By passing this flag, a local instance of the API server is temporarily spawned using the KubeConfig on the local system.

Since #1353, the registration of the `--local-server` flag has already been moved to commands where it makes sense instead of it being a global persistent flag. However, the setup for the server has remained at root level — making it a slightly awkward feature as the consumption happens at a higher level than the registration.

While this could potentially be refactored to at least abstract the local server away, and only spawn it in places where it is strictly required. Doing this in a nice manner, while dealing with the temporary listener and configuration of the address would continue to be challenge. In addition, one could arguably do about anything the API server is capable of by just using `kubectl` to either get, list or modify resources.

Given the above, I am wondering what the use case was/is for this feature, and if this still applies today and outweighs the technical challenges it introduces?

cc: @jessesuen

**Comment by krancour** [comment] 2024-03-05 00:01
I've always questioned the value of this local API server option...

Specifically, I question how often it will be that someone _isn't_ running the API server in the Kargo control plane. If someone isn't doing so, they're also not using the UI. I feel someone running Kargo in this manner already intends to just do everything via `kubectl`.

I am +1 on dropping this, but want to hear other perspectives.

I agree that it's worth asserting how valuable this is or isn't before putting any effort into cleaning up how it works.

**Comment by jessesuen** [comment] 2024-03-05 05:27
The value of the local API server was motivated by the following use case where:
* Kargo API server is **_not_** exposed in a shared manner
* End users are given access to a portion of the cluster via kubeconfig
* Users could still have a UI to do their thing

And so the local kargo dashboard option was intended to enable a cluster tenant user, who has read/write permissions to just a portion of the cluster (one or more namespaces), to run a local UI so they have an interface for managing their kargo environments. They could also avoid involve another team (e.g. cluster operator) who might control ingress to the cluster.

This design and access model is most analogous to the (now defunct) https://octant.dev/ project. Both Argo CD and Workflows have a similar local UI capability inspired by Octant.

That said, I'm not quite sure how popular these features are, and I'm okay eliminating the feature if it's causing us consternation.

But would that mean we build `kargo` CLI separate from `kargo-api` binaries?

**Comment by krancour** [comment] 2024-03-05 14:07
@jessesuen the use case you described makes sense, but cannot be done with the feature as currently implemented.

At present, adding `--local-server` to a command launches an ephemeral server that lives for the life of the command it's carrying out.

That means that "Users could still have a UI to do their thing" is definitely not a possibility.

If we changed things so the UI has an option to launch a local server that remains running until interrupted, that would seem to make more sense.

wdyt?

**Comment by jessesuen** [comment] 2024-03-05 20:39
> At present, adding --local-server to a command launches an ephemeral server that lives for the life of the command it's carrying out.

Hmmm, I think I did not realize that's what was going on. If that's the case, I don't think there is a need to have this option.

> If we changed things so the UI has an option to launch a local server that remains running until interrupted, that would seem to make more sense.

This is how I thought the feature worked. In fact, I was confused because it appears we have two CLI's, both named `kargo`.

There is the `kargo` CLI for the `kargo-api` and `kargo-controller` Deployments:

```Dockerfile
COPY --from=tools /tools/ /usr/local/bin/
COPY bin/controlplane/kargo /usr/local/bin/kargo

USER 1000:0

CMD ["/usr/local/bin/kargo"]
```

It starts the kargo API server with the command:
```
/usr/local/bin/kargo api
```

And then there's the CLI users download and run from their workstation. This one does not have the `api` subcommand:

```
$ kargo api
Error: unknown command "api" for "kargo"
Run 'kargo --help' for usage.
```

I think we should do a couple of things:
1. rename the kargo backend binaries to avoid the confusion I had (and I think others will too)
2. remove `--local-server`. I don't see value in starting and stopping the server for one command
3. **_Consider_** introducing a new Octant-like CLI feature for running local UI. This is not a priority for me, since we haven't yet implemented it and it would be a new/extra effort. That said, I think all it would entail is moving the `api` sub-command from the backend kargo CLI to the end-user `kargo` CLI.

**Comment by krancour** [comment] 2024-03-05 21:13
Thanks @jessesuen. I think we're all moving onto the same page here.

> I was confused because it appears we have two CLI's, both named kargo.

This was my doing. I hadn't imagined this causing much confusion, but I can see that I was wrong.

> rename the kargo backend binaries to avoid the confusion I had (and I think others will too)

`kargo-back-end` sound ok for the binary that we bake into the image?

> remove --local-server. I don't see value in starting and stopping the server for one command

:100:

> Consider introducing a new Octant-like CLI feature for running local UI. This is not a priority for me, since we haven't yet implemented it and it would be a new/extra effort. That said, I think all it would entail is moving the api sub-command from the backend kargo CLI to the end-user kargo CLI.

Adding `kargo server` would be trivial because the logic already exists in `--local-server`, which we'd be removing. And it serves the UI, which is accessible from `kargo dashboard`.

The only real effort -- which I agree would be the main impetus for deferring this -- would be implementing some kind of no-op login option for both the CLI and UI.

i.e., We'd want the option to `kargo login http://localhost:<some port>` in order to specify the API server to communicate with, _without_ any need for authenticating, since that particular API server will already be running with credentials from your kubeconfig.

Anyway... I think we could do two thirds of what's above with close to no effort and save the last 1/3 of it for a future release.

**Comment by hiddeco** [comment] 2024-03-05 21:44
> `kargo-back-end` sound ok for the binary that we bake into the image?

Maybe just `kargo-server`? Saves you from a double dash.

> The only real effort -- which I agree would be the main impetus for deferring this -- would be implementing some kind of no-op login option for both the CLI and UI.
>
> [..] without any need for authenticating, since that particular API server will already be running with credentials from your kubeconfig.

Am I following correctly, (the lack of) this is also the thing which prevents `--local-server` from working at all in its current shape?

**Comment by jessesuen** [comment] 2024-03-05 22:50
> Am I following correctly, (the lack of) this is also the thing which prevents --local-server from working at all in its current shape?

Not sure about the above, but +1 to `kargo-server`, at least vs. `kargo-back-end`.

**Comment by krancour** [comment] 2024-03-05 23:05
> Am I following correctly, (the lack of) this is also the thing which prevents --local-server from working at all in its current shape?

iirc, `--local-server` fires up the server _without_ any authn. Similar to `helm`, the server will use your `~/.kube/config` to talk to the cluster. So anyone who can talk to `localhost:whatever` (_not_ `0.0.0.0:whatever`) can use the API server to do anything their own cluster credentials would permit them to do anyway. (tbh, idk why this is currently resulting in authz errors.)

A theoretical `kargo server` command would work the same way.

The main difference between this and `--local-server` is that it requires somehow pointing `$XDG_CONFIG_HOME/kargo/config` at the local server at `localhost:whatever`. Presently one points the config at a particular server through `kargo login`, but we don't have an "authn-less" login option yet.






Re: `kargo-server` my only worry is that it doesn't head off _all_ confusion. The same binary launches non-server components like controller, management controller, and garbage collector.

**Comment by hiddeco** [comment] 2024-03-06 10:53
> (tbh, idk why this is currently resulting in authz errors.)

I have figured this out, I think. While we [do not configure](https://github.com/akuity/kargo/blob/ab3b21e3868fd6738a324cf10ac4534dced258fe/internal/api/option/option.go#L26-L31) an authn interceptor when the server is configured to be a local, we actually do rely on it injecting user information when we attempt to retrieve an authorized client: https://github.com/akuity/kargo/blob/ab3b21e3868fd6738a324cf10ac4534dced258fe/internal/api/kubernetes/client.go#L604-L607

Because of this (likely rightful) assumption, any request for an actual client will fail and the local API server will refuse to return results. I think this could potentially be solved by setting up an authn interceptor for a local server while marking the "user" as admin, which would cause it to simply return the internal client which has been set up using the local Kubeconfig:

https://github.com/akuity/kargo/blob/ab3b21e3868fd6738a324cf10ac4534dced258fe/internal/api/kubernetes/client.go#L609-L613

**Comment by krancour** [comment] 2024-03-06 14:07
@hiddeco you're right about the authorizing client wrapper getting in the way here. I hadn't suspected that at first, because I _thought_ we were passing an _unwrapped_ client here:

https://github.com/akuity/kargo/blob/main/cmd/cli/root.go#L58-L74

I know there's already a PR open to remove `--local-server`, but when we get around to `kargo server`, imho, we should just make the local server use a an unwrapped (non-authorizing) client.

**Comment by krancour** [comment] 2024-04-02 16:21
Closing in favor of #1728

**Closed by krancour** 2024-04-02 16:21 UTC
Labels: kind/discussion, area/cli, area/api, needs/priority, needs-discussion
