### ISSUE TITLE
Infinite loop when promoting image

### ISSUE THREAD

**Issue by stephaneetje** [akuity/kargo#2968] opened 2024-11-20 11:41 UTC
Hello, 

I've been trying to use kargo to only promote image tags (using helm-image-update) but on all my stages, i get an inifnite loop at the argocd-update step.

Here is my stage:

```
      steps:
        - config:
            checkout:
              - branch: main
                path: ./src
            repoURL: https://github.com/test/test-helm.git
          uses: git-clone
        - as: update-image
          config:
            images:
              - image: europe-docker.pkg.dev/test-001/test/scim
                key: image.tag
                value: Tag
            path: ./src/helm/scim/values-scim-staging-image.yaml
          uses: helm-update-image
        - as: commit
          config:
            messageFromSteps:
              - update-image
            path: ./src
          uses: git-commit
        - config:
            path: ./src
          uses: git-push
        - config:
            apps:
              - name: scim-staging
                sources:
                  - desiredCommitFromStep: commit
                    repoURL: https://github.com/test/test-helm.git
          uses: argocd-update
```

I also tried removing `desiredCommitFromStep` but didn't change anything.
My warehouse is only subscribing an image repository:

```
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    kargo.akuity.io/color: black
  name: scim-prod
  namespace: scim
spec:
  subscriptions:
  - image:
      imageSelectionStrategy: SemVer
      repoURL: europe-docker.pkg.dev/test-01/test/scim
      discoveryLimit: 10
      allowTags: ^v(\d+\.)?(\d+\.)?(\*|\d+)$
```

You can see in the Argocd app's envents that it is looping
<img width="1188" alt="Capture d’écran 2024-11-20 à 12 38 54" src="https://github.com/user-attachments/assets/53389d9b-ddd1-4ff0-b7b9-e91d6f317fa7">

Discussion has began on [this issue](https://github.com/akuity/kargo/issues/2952), opening another one as asked by @krancour

**Comment by krancour** [comment] 2024-11-20 12:54
@stephaneetje my apologies, as I seem to have misunderstood the nature of your loop. With the previous discussion having taken place in a thread about `desiredCommit`, I was misled into believing that to have been an actual factor in your problem. If you leave that field alone, as you are currently, AND if there is no commit in your Freight, then when syncing an App, Kargo has no notion of what specific revision that App should observably be synced to once complete.

This means the cause of your loop has nothing to do with a mismatch of the desired revision.

The continuous syncing is _probably_ due to the argocd-update step syncing, then when checking to see if the sync completed, discovering that the most recently completely sync wasn't the one _it_ asked for. It's waiting for its request to complete and seeing _a_ sync completed, but that operation must have been initiated by someone or something else, so it tries again.

Do you happen to have auto-sync enabled on your Apps? It is possible _that_ is what the update step is fighting a losing battle against. We do generally suggest disabling autosync oh Apps when you use Kargo. I will address it in the docs to make that more clear.

If this ends up not being the issue, enabling debug logging on the controller should provide more insight into what conditions are causing the update step to be caught in this sync loop.

**Comment by krancour** [comment] 2024-11-20 15:41
> I verified and sync is comming from Kargo

Oh. I had no doubt of that.

The mystery is why Kargo is syncing over and over again -- which would usually be because:

1. It initiates a sync operation
2. It follows up on the status of the last operation
3. Finds something unsatisfactory about the status of the last operation
4. Tries again

I'm trying to piece together what's going wrong at step 3 and it was conjecture that something _besides_ Kargo might also be initiating syncs.

I am attempting to replicate this.

**Comment by hiddeco** [comment] 2024-11-20 17:13
Running a build with #2936 in it should make it much easier to trace the reason without having to try to reproduce it.

**Comment by hiddeco** [comment] 2024-11-20 17:48
> Running a build with #2936 in it should make it much easier to trace the reason without having to try to reproduce it.

`ghcr.io/hiddeco/kargo:1.0.4-rc.66550612` built from our `release-1.0` branch should log the reason for the infinite loop, if any.

**Comment by hghtwr** [comment] 2024-11-20 18:31
I have the same problem and this is what I found in the logs: 
```
time="2024-11-20T18:21:15Z" level=debug msg="sync result revisions [0b8559a96d3441da09b2c84f6bd85f8fa06e56d1] do not match desired revisions [62429f4247599ff1746023c29e4514e24dee322e]" freight=d82c676db847dce25b54c3328801ec10fae9592b namespace=kargo-poc-tags promotion=teststable-tags.01jd5cw76w9waj367f69rsk1ek.d82c676 stage=teststable-tags
```

While `0b8559` being the head of the branch (with new manifests in a separate folder) and `62429f` being the commit the freight originated from.

**Comment by stephaneetje** [comment] 2024-11-20 19:22
@krancour  i just tried with only the name :
```
      - uses: argocd-update
        config:
          apps:
            - name: scim-staging
```

Step passes well, but i end up with the application being synced successfully (not with the latest comit which is kargo one's with the image update), then outofsync (image has not been updated). I have to do another manual sync...

**Comment by krancour** [comment] 2024-11-20 21:42
> Step passes well, but i end up with the application being synced successfully, then outofsync (image has not been updated). I checked the revision used by the sync, it is the good one with the image change.

This has the appearance of an Argo CD quirk/issue and not a Kargo issue.

> Also kargo documentation sais that apps[].sources[].repoURL is mandatory, thats why i had it before, and because i thought that would make sure the synced commit is the one from precedent step.

Ahhhhh. This explains everything. 😄 I had not noticed that source update.

`sources` isn't mandatory. `repoURL` is mandatory _on_ each source, if you specify any, that is. That is for updating individual sources of the Application -- which is something you have no need to do. All you want to do is trigger a sync.

When you _do_ perform any kind of updates on a source, there's a whole additional layer of stuff that happens when checking if the sync was successful. It compares what the sources look like to what you _want_ them to look like. The discrepancy was here (somehow?) and because of it, the sync was being re-attempted over and over again because it kept looking like it hadn't worked.

**Comment by andrii-korotkov-verkada** [comment] 2024-11-21 20:17
Does Kargo wait for refresh to finish before sending a sync signal?

**Comment by krancour** [comment] 2024-11-21 21:26
We send patch the Application with a sync operation. Argo CD automatically refreshes before a sync. So the short answer is no. The longer answer is, "no because there's no need."

After we sync is initiated, Kargo follows up on it as many times as necessary to find evidence that the exact sync operation it initiated has since completed.

**Comment by andrii-korotkov-verkada** [comment] 2024-11-21 22:26
Seems like app starts showing out of sync only when sync is already running, indicating there can be some race. Idk about exact reasons though.

**Comment by andrii-korotkov-verkada** [comment] 2024-11-22 14:31
> We patch the Application with a sync operation.

Do you mean you patch the application sync operation directly instead of calling the server endpoint to do so? That might explain what we saw when trying to repro using ArgoCD CLI and being unable to. I'm pretty sure some steps are missing to do sync properly. How hard would it be to just trigger sync via endpoint/calling the code instead of patching the application?

**Comment by andrii-korotkov-verkada** [comment] 2024-11-22 14:32
In particular, the observed behavior in ArgoCD UI is that Sync is clickable, shows a new duration, but shows old sync's data for a few seconds. This doesn't look intended.

**Comment by krancour** [comment] 2024-11-22 16:10
This doesn't sound like a Kargo problem.

Note that #2980 should probably fix the original problem described by this thread.

**Comment by andrii-korotkov-verkada** [comment] 2024-11-22 17:14
@krancour, I don't think ArgoCD is expected to work correctly with surgical replacements of things that are supposed to be done by using more high-level APIs. The evidence of showing both old and new data in the Sync info for a bit only supports that, at least that Kargo doesn't update the sync operation on the app properly. But operation state seems like an internal field managed by ArgoCD, so manually updating it doesn't seem like it should be done. It's like using library's internal function.

**Comment by krancour** [comment] 2024-11-22 19:15
> I don't think ArgoCD is expected to work correctly with surgical replacements of things that are supposed to be done by using more high-level APIs

I'm afraid this is incorrect. When you sync an App via Argo CD API, it's merely a _request_ to sync and is handled the same way we do it. i.e. It patches the application with a sync operation:

https://github.com/argoproj/argo-cd/blob/32cc6638f78e15652c24eb2cd6403e6e7ec26ab0/server/application/application.go#L1968-L1993

In either case, it is the Application controller that is doing all the actual work.

**Comment by krancour** [comment] 2024-11-22 19:46
The original issue here should be closed by #2980.

**Closed by krancour** 2024-11-22 19:46 UTC
Labels: kind/bug, needs/priority, needs/area

**Comment by andrii-korotkov-verkada** [comment] 2024-11-22 21:46
How does Kargo patch the manifest? Can you point me to the code, please? What if ArgoCD controller changes the way it patches?

**Comment by jessesuen** [comment] 2024-11-22 23:23
Kargo is indeed setting the `.operation` field in the App object. While this might seem potentially fragile, this was an intentional design choice so that Kargo could avoid interfacing with Argo CD API server entirely, which would require supplying Kargo with Argo CD auth credentials, as well as other tradeoffs.

> What if ArgoCD controller changes the way it patches?

Kargo would have to adapt. We do copy the implementation:

* [Kargo](https://github.com/argoproj/argo-cd/blob/master/util/argo/argo.go#L810)
* [ArgoCD](https://github.com/argoproj/argo-cd/blob/32cc6638f78e15652c24eb2cd6403e6e7ec26ab0/util/argo/argo.go#L809) 

However, I'm comfortable with this design choice, having **_wrote_** the original Argo CD code and understanding that the sync operation logic has not changed in incompatible way since basically its inception.

As Kent already pointed out, we are merely **_requesting_** the sync operation by setting the initial `.operation` field but the controller is the one updating that field thereafter. What Kargo is doing is pretty safe, and _relatively_ future proof. Any future Argo CD changes we would be aware of ahead of time and prepared to deal with.

**Comment by andrii-korotkov-verkada** [comment] 2024-11-23 00:22
@jessesuen, the Kargo link points to ArgoCD repo. I think I've found the relevant code though https://github.com/akuity/kargo/blob/cc293f0bd128943e097d9ae76ea69469b7a1c462/internal/directives/argocd_updater.go#L476.

When comparing it with SetAppOperation, I don't see an analog to clearing `app.Status.OperationState` https://github.com/argoproj/argo-cd/blob/32cc6638f78e15652c24eb2cd6403e6e7ec26ab0/util/argo/argo.go#L820. Maybe that what's leading to previous sync metadata being shown in a case @stephaneetje described.

I've seen different approaches for constructing the operation in server and app controller https://github.com/argoproj/argo-cd/blob/32cc6638f78e15652c24eb2cd6403e6e7ec26ab0/server/application/application.go#L1968-L1985, https://github.com/argoproj/argo-cd/blob/32cc6638f78e15652c24eb2cd6403e6e7ec26ab0/controller/appcontroller.go#L1987-L2051. Comparing with manual sync in server, Kargo doesn't set prune for example. Comparing with automated sync in controller, it doesn't do checks for already attempted syncs, tho some of it is specific to autosync's options. There are more differences, but I'm not sure they'd case the behavior described.

Overall, I think clearing the app.Status.OperationState needs to be added. As for Prune etc., not sure if Kargo has controls for this, but should be updates as well if yes.

**Comment by krancour** [comment] 2024-11-23 01:12
> Comparing with manual sync in server, Kargo doesn't set prune for example.

This is correct. There are options it doesn't set. There is no reason that certain high-value options cannot be surfaced in the `argocd-update` step. Please open a separate issue please if there is a setting you mean to ask for.

> Overall, I think clearing the app.Status.OperationState needs to be added.

It's not clear what you think this will accomplish.

Great care is taken already to verify that a completed operation is the exact operation we requested. This is accomplished by comparing the details of `app.Status.OperationState` (set by the Application controller) against the details of the Promotion. If it doesn't match, we request a new sync. (This is actually how the infinite loop, which was the original subject of this thread, was happening. There was a discrepancy in the details and that has been fixed.)

Here is the relevant code:

https://github.com/akuity/kargo/blob/cc293f0bd128943e097d9ae76ea69469b7a1c462/internal/directives/argocd_updater.go#L365-L474

**Comment by andrii-korotkov-verkada** [comment] 2024-11-23 01:37
> This is correct. There are options it doesn't set. There is no reason that certain high-value options cannot be surfaced in the argocd-update step. Please open a separate issue please if there is a setting you mean to ask for.

Here we go https://github.com/akuity/kargo/issues/2984.

> It's not clear what you think this will accomplish.

Parity with how ArgoCD does things, as well as consistency of the state. If the previous sync has finished and we add a new operation, keeping old status's operation state would not reflect the operation and probably results in the UI inconsistency showing new sync started, but state of the previous sync.

I'll open a separate issue for this though.

**Comment by andrii-korotkov-verkada** [comment] 2024-11-23 01:49
@jessesuen, @krancour, I've created https://github.com/akuity/kargo/issues/2985.
