### ISSUE TITLE
update quickstart to not use dockerhub

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#2184] opened 2024-06-20 17:12 UTC
The example currently used by the quickstart involves a subscription to the nginx image on DockerHub. There is a high probability of users trying the quickstart being rate-limited.

We should update the quickstart to use an image that isn't hosted on DockerHub.

**Comment by jessesuen** [comment] 2024-06-20 22:35
Duplicate of https://github.com/akuity/kargo/issues/1966.

But will add the concern of not to use dockerhub because of rate limits.

**Closed by jessesuen** 2024-06-20 22:35 UTC
Labels: needs/kind, needs/priority, needs/area
