### ISSUE TITLE
UI randomly reorders the Project card view

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1734] opened 2024-04-02 19:51 UTC
# Description

Visit the kargo root page (e.g. https://kargo.demo.akuity.io/), then click refresh a bunch of times. Project list will reorder randomly.

# Version

```
v0.5.0
```

**Comment by krancour** [comment] 2024-04-02 23:33
Duplicate of #782

**Closed by krancour** 2024-04-02 23:33 UTC
Labels: kind/bug, area/ui, priority/normal
