### ISSUE TITLE
update-yaml directive

### ISSUE THREAD

**Issue by mmclane** [akuity/kargo#2901] opened 2024-11-05 18:29 UTC
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.
* [x] I've pasted the output of `kargo version`, if applicable.
* [x] I've pasted logs, if applicable.

# Proposed Feature

I want a directive that I can use in my promotionTemplate that will allow me to update any yaml value to a know piece of information.  This would be similar to the helm-update-image but I would be able to give it any yaml file and a key and a value to set it to.  This could then get committed with a later step.

# Motivation

We don't have a method for updating the targetRevision value on an Argo Application manifest that is stored in git and then synced via Argo CD.   As is stated in the Kargo documentation 

> Without making any modifications to a Git repository, this example simply updates a "live" Argo CD Application resource to point its targetRevision field at a specific version of a Helm chart, which Argo CD will pull directly from the the chart repository.

I would like a way in my promotionTemplate to update the Application manifest in git.  I could then have kargo run an argocd-update against both the parent app and the child that I am updating to keep everything in sync.

My alternative is to ignore changes to the targetRevision in the parent and rely on ArgoCD's state, which as stated is not "real GitOps".

# Suggested Implementation

This could be achieved by adding an argocd-application-update directive that is similar to the helm-update-image directive.  I think however you would get more value if you just had an update-yaml directive that could take a known value (like tag or targetRevision) and use it to update a specified key in a specific file.  That would allow us to implement this solution and others.

![image](https://github.com/user-attachments/assets/5ed22ba7-70bd-4576-9c25-d0ba5fb46cb9)

**Comment by krancour** [comment] 2024-11-05 21:25
This is coming, but this is a duplicate of #2701. Closing so that we're tracking it in just one place.

**Closed by krancour** 2024-11-05 21:25 UTC
Labels: kind/enhancement, needs/priority, needs/area, kind/proposal
