### ISSUE TITLE
Multiple Verifications running for a Stage

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#2142] opened 2024-06-11 17:29 UTC
# Description

Stages seem to be allowing multiple Verifications to be run at the same time. Each coincided with a promotion.

<img width="865" alt="image" src="https://github.com/akuity/kargo/assets/12677113/b5d42d7b-3fe6-4b54-bd91-241cf4ab852a">

```
$ k get ar
NAME                                     STATUS    AGE
dev.01j02dz4tbp75sf7zmvgkw3d3j.9e5f6ab   Failed    16h
dev.01j02hycta7xsjz7xczamptk6c.9d167fb   Failed    14h
dev.01j03w1h1njwvj432nbh8m7xvk.a72c52c   Running   158m
dev.01j03wxxntp3a3xm5pbpdzzzkd.bd13218   Running   142m
dev.01j03z1dzstgnx5tw85ty3apxr.97465d1   Running   105m
```

I feel that we should only be allowing one at a time to happen. 

We should also decide how Promotion should affect currently running Verifications. e.g. should it:
* wait for current verification to complete, then immediately launch a new one against the freight?
* terminate in-flight verification (since it's ambiguous what exactly was verified)?
* block the promotion until verification is completed?

# Steps to Reproduce

Promote something else while a verification is already running.

# Version

```
v0.7.0
```

**Comment by krancour** [comment] 2024-06-11 19:20
Possibly a duplicate of #2128?

**Comment by hiddeco** [comment] 2024-06-11 20:05
> block the promotion until verification is completed?

I feel this would (again) steer more towards verification being an element of promotion, which based on the further discussion in #2128 does not appear to be true. In addition, it hypothetically opens a gap to e.g. quickly issue re-verifications to block a promotion from ever starting.

Given this, I am inclined to say we should wait for a running verification to complete (and _maybe_ terminate it if there is new current Freight), before triggering a new verification.

**Comment by krancour** [comment] 2024-06-11 21:49
> which based on the further discussion in https://github.com/akuity/kargo/issues/2128...

fwiw, my thoughts there were in no way definitive/final.

Let's hash this out f2f when time permits.

**Comment by krancour** [comment] 2024-08-19 16:02
Close enough to a duplicate of #2128 that I am closing this one to keep discussion all in one place.

**Closed by krancour** 2024-08-19 16:02 UTC
Labels: kind/bug, priority/normal, area/controller
