### ISSUE TITLE
git-push subject to race conditions when many stages push to same mono repo

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#3071] opened 2024-12-05 20:46 UTC
# Description

Two or more stages might attempt to push to same repo at the same time (e.g. using promote downstream button). When this happens, the git-push step might intermittently fail like:

`
step execution failed: failed to run step "git-push": error pushing commits to remote: error pushing branch: error executing cmd [/usr/bin/git push origin HEAD]: remote: Bypassed rule violations for refs/heads/main: remote: remote: - Changes must be made through a pull request. remote: To https://github.com/example/guestbook-deploy.git ! [remote rejected] HEAD -> main (cannot lock ref 'refs/heads/main': is at 74291c2cb80ee3f5c6e5e6e329e13a5a1866ca61 but expected 473aff63b3da037e6c6d4a3de2dabaee3c196c83) error: failed to push some refs to 'https://github.com/example/guestbook-deploy.git'
`

A workaround may be to use the retry feature, but I haven't verified this.

# Steps to Reproduce

Have multiple stages promoting at same time while modifying the same gitops repo. Timing should try to overlap 

# Version

```
v1.2.0-unstable-20241205
```

**Comment by krancour** [comment] 2024-12-05 20:49
A workaround may be to use the retry feature, but I haven't verified this.

I don't think retry will work. It will just retry the _same_ push.

This was discussed offline on Monday and @hiddeco's suggestion had been to make the `push` step able to detect when the local branch is behind the remote and rebase.

If multiple Stages are working with the same branch, they should at least be working with different files, so merge conflicts should be rare.

**Comment by hiddeco** [comment] 2024-12-05 21:06
I think there are a couple of additional error strings which we should look for:

- non-fast-forward errors: https://docs.github.com/en/get-started/using-git/dealing-with-non-fast-forward-errors
- fetch first errors: https://stackoverflow.com/questions/25862329/git-giving-fetch-first-error-when-trying-to-push

The easiest way to rebase is likely: `git pull --rebase`.

**Comment by krancour** [comment] 2024-12-06 01:35
@hiddeco instead of trying the push and then looking for specific error messages, what if we _pre-emptively_ pull --rebase?

**Comment by hiddeco** [comment] 2024-12-09 16:13
Assuming that when this still fails, we can retry the step if such a configuration is set — I think this could work.

**Comment by krancour** [comment] 2024-12-09 20:06
> Assuming that when this still fails, we can retry the step if such a configuration is set — I think this could work.

I don't think retrying the _step_ changes much, right? If there's a merge conflict that cannot be resolved automatically with a rebase, I think we'd need to retry the whole promotion process from the beginning. I'm not opposed to that, but "retry everything" seems like its own separate feature.

**Comment by ksawerykarwacki** [comment] 2024-12-10 12:41
This is a critical blocker, without it you effectively cannot have more than one flow (warehouse + stages) or multiple projects working on single repo. Effectively forcing everyone into multirepo approach even if they use different branches for distinct stages (but stages contain multiple apps as you can end up with the race condition).

**Comment by hiddeco** [comment] 2024-12-10 14:24
> I don't think retrying the step changes much, right?

My retry was aimed at the scenario where there would still be a new push from another Promotion between the time the Promotion does a `git pull --rebase` and a `git push`, which hypothetically is possible and _could_ be retried.

**Comment by krancour** [comment] 2024-12-10 14:55
Ah. That makes sense.

**Comment by krancour** [comment] 2024-12-10 15:01
> This is a critical blocker, without it you effectively cannot have more than one flow (warehouse + stages) or multiple projects working on single repo. Effectively forcing everyone into multirepo approach even if they use different branches for distinct stages (but stages contain multiple apps as you can end up with the race condition).

We're aware of the problem this poses, which is why we opened the issue.

You're overstating the implications a bit, however. This does not force you into using multiple repositories.

The problem is simply one of multiple Promotion processes _writing_ to the same branch. If you consume charts or templates or something from the `main` branch of your monorepo, but write relevant, updated, or rendered parts to a Stage-specific branch (which you even mention) then there it no issue at all and you need not use multiple repos.

**Comment by ksawerykarwacki** [comment] 2024-12-10 15:27
@krancour yes but this assumes that you have one promotion flow per repository. Theoretically you can have multiple promotion flows (e.g. one per app or team) which may use shared stages (e.g. specific Kubernetes clusters) in monorepo. As there is no locking between promotion flows / projects on access to repo you can end up with this race condition easily. 

Of course, this is not an issue if you have one project and shared steps for multiple warehouses, but I assume that many teams (including mine) would prefer to have deeper separation of promotion flows. It might be an antipattern but if that is the case then this should be highlighted in the documentation which currently lacks examples for scaling and multitenancy handling.

It might not be a big issue from technical perspective, but this leads to unpleasant experience for everyone trying to adopt Kargo to their workflow (I run into it within 10 minutes after my first installation) which may discourage some folks.

**Comment by krancour** [comment] 2024-12-10 16:12
I will re-iterate that the only problem is multiple stages _writing to the same branch._ If that is not something you are doing, there is no problem.

If it is something you are doing, then the fix will be in 1.2 or possibly even in 1.1.2.

**Closed** 2024-12-17 17:21 UTC
Labels: kind/bug, priority/high, area/controller
