### ISSUE TITLE
bug: stage freight may appear as EMPTY

### ISSUE THREAD

**Issue by evgeny-goldin** [akuity/kargo#2094] opened 2024-06-03 18:33 UTC
* Kargo version is `0.6.0`
* We have 3 stages: `dev`, `test`, `staging`
* At a certain point all 3 stages had the same Freight promoted - `"waxen-seal"`
* I leave the Kargo page open for a while. While I'm away - `dev` and `test` stages were auto-promoted to a newer Freight.
* However the page now displays these stages as `EMPTY`

  <img src="https://github.com/akuity/kargo/assets/117124/117c150f-cec2-47fe-a8a5-f5e47dd4c6cf" width="300"/>

* If the page is reloaded - the correct Freight now shows up for auto-promoted stages:

  <img src="https://github.com/akuity/kargo/assets/117124/b9bfadcb-4e53-4b4d-a886-e6573b658c2b" width="300"/>

# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [ ] I've pasted logs, if applicable.

# Description

# Screenshots

# Steps to Reproduce

# Version

```
Paste the output from `kargo version` here.
```

# Logs

```
Paste any relevant application logs here.
```

**Comment by rbreeze** [comment] 2024-06-04 16:53
@evgeny-goldin Can you try reproducing this on `main`? There were quite a few UI performance improvements and refactors since 0.6.0 got merged, and I can't reproduce this, so I think there's a good chance this was fixed.

In the meantime I'm looking through commits to see if I can pinpoint the change that would have fixed it

**Closed** 2024-06-04 16:56 UTC
Labels: kind/bug, needs/priority, needs/area

**Comment by evgeny-goldin** [comment] 2024-06-04 17:00
Thank you, @rbreeze ! Good to know it's fixed.
